version: '3'

services:

  backend:
    build: ./app/backend/
    expose:
      - 3000
    volumes:
      - "/Users/sergei/volumes/pr-legacy/upload/:/home/nodejs/upload/"
    depends_on:
      - nginx
    environment:
      - VIRTUAL_HOST=localhost
      - PORT=3000

  nginx:
      image: jwilder/nginx-proxy
      container_name: balancer
      volumes:
        - "/var/run/docker.sock:/tmp/docker.sock:ro"
      ports:
        - 3200:80
