version: '3'

services:

  backend:
    build: ./app/backend/
    expose:
      - 3000
    depends_on:
      - db
      - nginx
    environment:
      - VIRTUAL_HOST=localhost
      - PORT=3000
      - DB_URL=mongodb://db:27017/sky-satellite

  nginx:
      image: jwilder/nginx-proxy
      volumes:
        - "/var/run/docker.sock:/tmp/docker.sock:ro"
      ports:
        - 3200:80

  db:
      image: "mongo"
      ports:
        - 3100:27017
